export * from '@pages/error/Error'
export * from '@pages/home/Home'
export * from '@pages/admin/Admin'
export * from '@pages/admin/addarticle/AddArticle'
export * from '@pages/home/articledetail/ArticleDetail'
export * from '@pages/admin/editarticle/EditArticle'
export * from '@pages/Person/Person'
export * from '@pages/VideoPage/VideoPage'